services:
  - type: web
    name: epi-electronics
    env: static
    buildCommand: npm run build && cp public/_redirects dist/
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
